### ISSUE TITLE
Add a V4 version of the Bounded Context Canvas

### ISSUE THREAD

**Issue by Nagelfar** [trustbit/Contexture#36]
In addition to the existing V3 version of the canvas the [recently published](https://github.com/ddd-crew/bounded-context-canvas) V4 version should be supported as the default way.

Note: the V4 does not introduce new concepts into the Bounded Context Canvas, but rather simplified and streamlined existing concepts and improved the wording.

**Comment by thomas-burko** [comment]
Implemented with https://github.com/trustbit/Contexture/pull/111
